# This is a sample build configuration for Python.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
image: python:3.6

pipelines:
  default:
    - step:
        script:
          - python --version
          - pip --version
          - python setup.py build
          - python -m unittest discover tests/ -v
  branches:
    master:
      - step:
          image: themattrix/tox
          script:
            - pip install -U coverage
            - python --version
            - pip --version
            - tox --version
            - python setup.py build
            - python -m unittest discover tests/ -v
            - tox
            - coverage report -i --include="signac*"
    develop:
      - step:
          image: themattrix/tox
          script:
            - pip install -U coverage
            - python --version
            - pip --version
            - tox --version
            - python setup.py build
            - python -m unittest discover tests/ -v
            - tox
            - coverage report -i --include="signac*"
    v*:
      - step:
          image: themattrix/tox
          script:
            - pip install -U coverage
            - python --version
            - pip --version
            - tox --version
            - python setup.py build
            - python -m unittest discover tests/ -v
            - tox
            - coverage report -i --include="signac*"
  tags:
   v*:
     - step:
          image: themattrix/tox
          script:
            - pip install -U coverage
            - pip install -U twine
            - python --version
            - pip --version
            - tox --version
            - twine --version
            - python setup.py build
            - python -m unittest discover tests/ -v
            - tox
            - coverage report -i --include="signac*"
            - .deploy.bash
