# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: style check
          command: |
            pip install --user -U flake8
            python -m flake8 --show-source signac/

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -U coverage

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover tests/ -v
            coverage run --source=signac/ -m unittest discover tests/
            coverage report -i --include="signac*"

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - run:
          name: benchmark
          command: |
            . venv/bin/activate
            pip install -U gitpython psutil pandas tqdm
            python benchmark.py run -N 100 1000  # this revision
            python benchmark.py report
            git reset --hard origin/master
            git checkout "${CIRCLE_SHA1}" -- benchmark.py  # ensure that we use the same benchmark script
            python benchmark.py run -N 100 1000 --force
            python benchmark.py compare origin/master "${CIRCLE_SHA1}"
